/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SwellLifeImport } from './routes/swell-life'
import { Route as StrettoInvoicesPaymentsImport } from './routes/stretto-invoices-payments'
import { Route as StrettoEballotImport } from './routes/stretto-eballot'
import { Route as SolvablyImport } from './routes/solvably'
import { Route as SeriousErpImport } from './routes/serious-erp'
import { Route as ResumeImport } from './routes/resume'
import { Route as ProjectsImport } from './routes/projects'
import { Route as MiamahComedyImport } from './routes/miamah-comedy'
import { Route as MarineInstituteImport } from './routes/marine-institute'
import { Route as MakotoImport } from './routes/makoto'
import { Route as HolyCityImport } from './routes/holy-city'
import { Route as HawaiiWildlifeFundImport } from './routes/hawaii-wildlife-fund'
import { Route as GymSyncImport } from './routes/gym-sync'
import { Route as ErrorImport } from './routes/error'
import { Route as ContactImport } from './routes/contact'
import { Route as ChicosZoomImport } from './routes/chicos-zoom'
import { Route as ChicosSimplySomaImport } from './routes/chicos-simply-soma'
import { Route as ChicosShopThisLookImport } from './routes/chicos-shop-this-look'
import { Route as CadenceDesignSystemImport } from './routes/cadence-design-system'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SwellLifeRoute = SwellLifeImport.update({
  id: '/swell-life',
  path: '/swell-life',
  getParentRoute: () => rootRoute,
} as any)

const StrettoInvoicesPaymentsRoute = StrettoInvoicesPaymentsImport.update({
  id: '/stretto-invoices-payments',
  path: '/stretto-invoices-payments',
  getParentRoute: () => rootRoute,
} as any)

const StrettoEballotRoute = StrettoEballotImport.update({
  id: '/stretto-eballot',
  path: '/stretto-eballot',
  getParentRoute: () => rootRoute,
} as any)

const SolvablyRoute = SolvablyImport.update({
  id: '/solvably',
  path: '/solvably',
  getParentRoute: () => rootRoute,
} as any)

const SeriousErpRoute = SeriousErpImport.update({
  id: '/serious-erp',
  path: '/serious-erp',
  getParentRoute: () => rootRoute,
} as any)

const ResumeRoute = ResumeImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const MiamahComedyRoute = MiamahComedyImport.update({
  id: '/miamah-comedy',
  path: '/miamah-comedy',
  getParentRoute: () => rootRoute,
} as any)

const MarineInstituteRoute = MarineInstituteImport.update({
  id: '/marine-institute',
  path: '/marine-institute',
  getParentRoute: () => rootRoute,
} as any)

const MakotoRoute = MakotoImport.update({
  id: '/makoto',
  path: '/makoto',
  getParentRoute: () => rootRoute,
} as any)

const HolyCityRoute = HolyCityImport.update({
  id: '/holy-city',
  path: '/holy-city',
  getParentRoute: () => rootRoute,
} as any)

const HawaiiWildlifeFundRoute = HawaiiWildlifeFundImport.update({
  id: '/hawaii-wildlife-fund',
  path: '/hawaii-wildlife-fund',
  getParentRoute: () => rootRoute,
} as any)

const GymSyncRoute = GymSyncImport.update({
  id: '/gym-sync',
  path: '/gym-sync',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const ChicosZoomRoute = ChicosZoomImport.update({
  id: '/chicos-zoom',
  path: '/chicos-zoom',
  getParentRoute: () => rootRoute,
} as any)

const ChicosSimplySomaRoute = ChicosSimplySomaImport.update({
  id: '/chicos-simply-soma',
  path: '/chicos-simply-soma',
  getParentRoute: () => rootRoute,
} as any)

const ChicosShopThisLookRoute = ChicosShopThisLookImport.update({
  id: '/chicos-shop-this-look',
  path: '/chicos-shop-this-look',
  getParentRoute: () => rootRoute,
} as any)

const CadenceDesignSystemRoute = CadenceDesignSystemImport.update({
  id: '/cadence-design-system',
  path: '/cadence-design-system',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cadence-design-system': {
      id: '/cadence-design-system'
      path: '/cadence-design-system'
      fullPath: '/cadence-design-system'
      preLoaderRoute: typeof CadenceDesignSystemImport
      parentRoute: typeof rootRoute
    }
    '/chicos-shop-this-look': {
      id: '/chicos-shop-this-look'
      path: '/chicos-shop-this-look'
      fullPath: '/chicos-shop-this-look'
      preLoaderRoute: typeof ChicosShopThisLookImport
      parentRoute: typeof rootRoute
    }
    '/chicos-simply-soma': {
      id: '/chicos-simply-soma'
      path: '/chicos-simply-soma'
      fullPath: '/chicos-simply-soma'
      preLoaderRoute: typeof ChicosSimplySomaImport
      parentRoute: typeof rootRoute
    }
    '/chicos-zoom': {
      id: '/chicos-zoom'
      path: '/chicos-zoom'
      fullPath: '/chicos-zoom'
      preLoaderRoute: typeof ChicosZoomImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/gym-sync': {
      id: '/gym-sync'
      path: '/gym-sync'
      fullPath: '/gym-sync'
      preLoaderRoute: typeof GymSyncImport
      parentRoute: typeof rootRoute
    }
    '/hawaii-wildlife-fund': {
      id: '/hawaii-wildlife-fund'
      path: '/hawaii-wildlife-fund'
      fullPath: '/hawaii-wildlife-fund'
      preLoaderRoute: typeof HawaiiWildlifeFundImport
      parentRoute: typeof rootRoute
    }
    '/holy-city': {
      id: '/holy-city'
      path: '/holy-city'
      fullPath: '/holy-city'
      preLoaderRoute: typeof HolyCityImport
      parentRoute: typeof rootRoute
    }
    '/makoto': {
      id: '/makoto'
      path: '/makoto'
      fullPath: '/makoto'
      preLoaderRoute: typeof MakotoImport
      parentRoute: typeof rootRoute
    }
    '/marine-institute': {
      id: '/marine-institute'
      path: '/marine-institute'
      fullPath: '/marine-institute'
      preLoaderRoute: typeof MarineInstituteImport
      parentRoute: typeof rootRoute
    }
    '/miamah-comedy': {
      id: '/miamah-comedy'
      path: '/miamah-comedy'
      fullPath: '/miamah-comedy'
      preLoaderRoute: typeof MiamahComedyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeImport
      parentRoute: typeof rootRoute
    }
    '/serious-erp': {
      id: '/serious-erp'
      path: '/serious-erp'
      fullPath: '/serious-erp'
      preLoaderRoute: typeof SeriousErpImport
      parentRoute: typeof rootRoute
    }
    '/solvably': {
      id: '/solvably'
      path: '/solvably'
      fullPath: '/solvably'
      preLoaderRoute: typeof SolvablyImport
      parentRoute: typeof rootRoute
    }
    '/stretto-eballot': {
      id: '/stretto-eballot'
      path: '/stretto-eballot'
      fullPath: '/stretto-eballot'
      preLoaderRoute: typeof StrettoEballotImport
      parentRoute: typeof rootRoute
    }
    '/stretto-invoices-payments': {
      id: '/stretto-invoices-payments'
      path: '/stretto-invoices-payments'
      fullPath: '/stretto-invoices-payments'
      preLoaderRoute: typeof StrettoInvoicesPaymentsImport
      parentRoute: typeof rootRoute
    }
    '/swell-life': {
      id: '/swell-life'
      path: '/swell-life'
      fullPath: '/swell-life'
      preLoaderRoute: typeof SwellLifeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cadence-design-system': typeof CadenceDesignSystemRoute
  '/chicos-shop-this-look': typeof ChicosShopThisLookRoute
  '/chicos-simply-soma': typeof ChicosSimplySomaRoute
  '/chicos-zoom': typeof ChicosZoomRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/gym-sync': typeof GymSyncRoute
  '/hawaii-wildlife-fund': typeof HawaiiWildlifeFundRoute
  '/holy-city': typeof HolyCityRoute
  '/makoto': typeof MakotoRoute
  '/marine-institute': typeof MarineInstituteRoute
  '/miamah-comedy': typeof MiamahComedyRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/serious-erp': typeof SeriousErpRoute
  '/solvably': typeof SolvablyRoute
  '/stretto-eballot': typeof StrettoEballotRoute
  '/stretto-invoices-payments': typeof StrettoInvoicesPaymentsRoute
  '/swell-life': typeof SwellLifeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cadence-design-system': typeof CadenceDesignSystemRoute
  '/chicos-shop-this-look': typeof ChicosShopThisLookRoute
  '/chicos-simply-soma': typeof ChicosSimplySomaRoute
  '/chicos-zoom': typeof ChicosZoomRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/gym-sync': typeof GymSyncRoute
  '/hawaii-wildlife-fund': typeof HawaiiWildlifeFundRoute
  '/holy-city': typeof HolyCityRoute
  '/makoto': typeof MakotoRoute
  '/marine-institute': typeof MarineInstituteRoute
  '/miamah-comedy': typeof MiamahComedyRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/serious-erp': typeof SeriousErpRoute
  '/solvably': typeof SolvablyRoute
  '/stretto-eballot': typeof StrettoEballotRoute
  '/stretto-invoices-payments': typeof StrettoInvoicesPaymentsRoute
  '/swell-life': typeof SwellLifeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cadence-design-system': typeof CadenceDesignSystemRoute
  '/chicos-shop-this-look': typeof ChicosShopThisLookRoute
  '/chicos-simply-soma': typeof ChicosSimplySomaRoute
  '/chicos-zoom': typeof ChicosZoomRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/gym-sync': typeof GymSyncRoute
  '/hawaii-wildlife-fund': typeof HawaiiWildlifeFundRoute
  '/holy-city': typeof HolyCityRoute
  '/makoto': typeof MakotoRoute
  '/marine-institute': typeof MarineInstituteRoute
  '/miamah-comedy': typeof MiamahComedyRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/serious-erp': typeof SeriousErpRoute
  '/solvably': typeof SolvablyRoute
  '/stretto-eballot': typeof StrettoEballotRoute
  '/stretto-invoices-payments': typeof StrettoInvoicesPaymentsRoute
  '/swell-life': typeof SwellLifeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cadence-design-system'
    | '/chicos-shop-this-look'
    | '/chicos-simply-soma'
    | '/chicos-zoom'
    | '/contact'
    | '/error'
    | '/gym-sync'
    | '/hawaii-wildlife-fund'
    | '/holy-city'
    | '/makoto'
    | '/marine-institute'
    | '/miamah-comedy'
    | '/projects'
    | '/resume'
    | '/serious-erp'
    | '/solvably'
    | '/stretto-eballot'
    | '/stretto-invoices-payments'
    | '/swell-life'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cadence-design-system'
    | '/chicos-shop-this-look'
    | '/chicos-simply-soma'
    | '/chicos-zoom'
    | '/contact'
    | '/error'
    | '/gym-sync'
    | '/hawaii-wildlife-fund'
    | '/holy-city'
    | '/makoto'
    | '/marine-institute'
    | '/miamah-comedy'
    | '/projects'
    | '/resume'
    | '/serious-erp'
    | '/solvably'
    | '/stretto-eballot'
    | '/stretto-invoices-payments'
    | '/swell-life'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cadence-design-system'
    | '/chicos-shop-this-look'
    | '/chicos-simply-soma'
    | '/chicos-zoom'
    | '/contact'
    | '/error'
    | '/gym-sync'
    | '/hawaii-wildlife-fund'
    | '/holy-city'
    | '/makoto'
    | '/marine-institute'
    | '/miamah-comedy'
    | '/projects'
    | '/resume'
    | '/serious-erp'
    | '/solvably'
    | '/stretto-eballot'
    | '/stretto-invoices-payments'
    | '/swell-life'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CadenceDesignSystemRoute: typeof CadenceDesignSystemRoute
  ChicosShopThisLookRoute: typeof ChicosShopThisLookRoute
  ChicosSimplySomaRoute: typeof ChicosSimplySomaRoute
  ChicosZoomRoute: typeof ChicosZoomRoute
  ContactRoute: typeof ContactRoute
  ErrorRoute: typeof ErrorRoute
  GymSyncRoute: typeof GymSyncRoute
  HawaiiWildlifeFundRoute: typeof HawaiiWildlifeFundRoute
  HolyCityRoute: typeof HolyCityRoute
  MakotoRoute: typeof MakotoRoute
  MarineInstituteRoute: typeof MarineInstituteRoute
  MiamahComedyRoute: typeof MiamahComedyRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  SeriousErpRoute: typeof SeriousErpRoute
  SolvablyRoute: typeof SolvablyRoute
  StrettoEballotRoute: typeof StrettoEballotRoute
  StrettoInvoicesPaymentsRoute: typeof StrettoInvoicesPaymentsRoute
  SwellLifeRoute: typeof SwellLifeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CadenceDesignSystemRoute: CadenceDesignSystemRoute,
  ChicosShopThisLookRoute: ChicosShopThisLookRoute,
  ChicosSimplySomaRoute: ChicosSimplySomaRoute,
  ChicosZoomRoute: ChicosZoomRoute,
  ContactRoute: ContactRoute,
  ErrorRoute: ErrorRoute,
  GymSyncRoute: GymSyncRoute,
  HawaiiWildlifeFundRoute: HawaiiWildlifeFundRoute,
  HolyCityRoute: HolyCityRoute,
  MakotoRoute: MakotoRoute,
  MarineInstituteRoute: MarineInstituteRoute,
  MiamahComedyRoute: MiamahComedyRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  SeriousErpRoute: SeriousErpRoute,
  SolvablyRoute: SolvablyRoute,
  StrettoEballotRoute: StrettoEballotRoute,
  StrettoInvoicesPaymentsRoute: StrettoInvoicesPaymentsRoute,
  SwellLifeRoute: SwellLifeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/cadence-design-system",
        "/chicos-shop-this-look",
        "/chicos-simply-soma",
        "/chicos-zoom",
        "/contact",
        "/error",
        "/gym-sync",
        "/hawaii-wildlife-fund",
        "/holy-city",
        "/makoto",
        "/marine-institute",
        "/miamah-comedy",
        "/projects",
        "/resume",
        "/serious-erp",
        "/solvably",
        "/stretto-eballot",
        "/stretto-invoices-payments",
        "/swell-life"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/cadence-design-system": {
      "filePath": "cadence-design-system.tsx"
    },
    "/chicos-shop-this-look": {
      "filePath": "chicos-shop-this-look.tsx"
    },
    "/chicos-simply-soma": {
      "filePath": "chicos-simply-soma.tsx"
    },
    "/chicos-zoom": {
      "filePath": "chicos-zoom.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/gym-sync": {
      "filePath": "gym-sync.tsx"
    },
    "/hawaii-wildlife-fund": {
      "filePath": "hawaii-wildlife-fund.tsx"
    },
    "/holy-city": {
      "filePath": "holy-city.tsx"
    },
    "/makoto": {
      "filePath": "makoto.tsx"
    },
    "/marine-institute": {
      "filePath": "marine-institute.tsx"
    },
    "/miamah-comedy": {
      "filePath": "miamah-comedy.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/resume": {
      "filePath": "resume.tsx"
    },
    "/serious-erp": {
      "filePath": "serious-erp.tsx"
    },
    "/solvably": {
      "filePath": "solvably.tsx"
    },
    "/stretto-eballot": {
      "filePath": "stretto-eballot.tsx"
    },
    "/stretto-invoices-payments": {
      "filePath": "stretto-invoices-payments.tsx"
    },
    "/swell-life": {
      "filePath": "swell-life.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
