/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SwellLifeImport } from './routes/swell-life'
import { Route as ResumeImport } from './routes/resume'
import { Route as ProjectsImport } from './routes/projects'
import { Route as MiamahComedyImport } from './routes/miamah-comedy'
import { Route as MakotoImport } from './routes/makoto'
import { Route as HolyCityImport } from './routes/holy-city'
import { Route as ErrorImport } from './routes/error'
import { Route as ContactImport } from './routes/contact'
import { Route as ChicosZoomImport } from './routes/chicos-zoom'
import { Route as ChicosSimplySomaImport } from './routes/chicos-simply-soma'
import { Route as ChicosShopThisLookImport } from './routes/chicos-shop-this-look'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SwellLifeRoute = SwellLifeImport.update({
  id: '/swell-life',
  path: '/swell-life',
  getParentRoute: () => rootRoute,
} as any)

const ResumeRoute = ResumeImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const MiamahComedyRoute = MiamahComedyImport.update({
  id: '/miamah-comedy',
  path: '/miamah-comedy',
  getParentRoute: () => rootRoute,
} as any)

const MakotoRoute = MakotoImport.update({
  id: '/makoto',
  path: '/makoto',
  getParentRoute: () => rootRoute,
} as any)

const HolyCityRoute = HolyCityImport.update({
  id: '/holy-city',
  path: '/holy-city',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const ChicosZoomRoute = ChicosZoomImport.update({
  id: '/chicos-zoom',
  path: '/chicos-zoom',
  getParentRoute: () => rootRoute,
} as any)

const ChicosSimplySomaRoute = ChicosSimplySomaImport.update({
  id: '/chicos-simply-soma',
  path: '/chicos-simply-soma',
  getParentRoute: () => rootRoute,
} as any)

const ChicosShopThisLookRoute = ChicosShopThisLookImport.update({
  id: '/chicos-shop-this-look',
  path: '/chicos-shop-this-look',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/chicos-shop-this-look': {
      id: '/chicos-shop-this-look'
      path: '/chicos-shop-this-look'
      fullPath: '/chicos-shop-this-look'
      preLoaderRoute: typeof ChicosShopThisLookImport
      parentRoute: typeof rootRoute
    }
    '/chicos-simply-soma': {
      id: '/chicos-simply-soma'
      path: '/chicos-simply-soma'
      fullPath: '/chicos-simply-soma'
      preLoaderRoute: typeof ChicosSimplySomaImport
      parentRoute: typeof rootRoute
    }
    '/chicos-zoom': {
      id: '/chicos-zoom'
      path: '/chicos-zoom'
      fullPath: '/chicos-zoom'
      preLoaderRoute: typeof ChicosZoomImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/holy-city': {
      id: '/holy-city'
      path: '/holy-city'
      fullPath: '/holy-city'
      preLoaderRoute: typeof HolyCityImport
      parentRoute: typeof rootRoute
    }
    '/makoto': {
      id: '/makoto'
      path: '/makoto'
      fullPath: '/makoto'
      preLoaderRoute: typeof MakotoImport
      parentRoute: typeof rootRoute
    }
    '/miamah-comedy': {
      id: '/miamah-comedy'
      path: '/miamah-comedy'
      fullPath: '/miamah-comedy'
      preLoaderRoute: typeof MiamahComedyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeImport
      parentRoute: typeof rootRoute
    }
    '/swell-life': {
      id: '/swell-life'
      path: '/swell-life'
      fullPath: '/swell-life'
      preLoaderRoute: typeof SwellLifeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chicos-shop-this-look': typeof ChicosShopThisLookRoute
  '/chicos-simply-soma': typeof ChicosSimplySomaRoute
  '/chicos-zoom': typeof ChicosZoomRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/holy-city': typeof HolyCityRoute
  '/makoto': typeof MakotoRoute
  '/miamah-comedy': typeof MiamahComedyRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/swell-life': typeof SwellLifeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chicos-shop-this-look': typeof ChicosShopThisLookRoute
  '/chicos-simply-soma': typeof ChicosSimplySomaRoute
  '/chicos-zoom': typeof ChicosZoomRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/holy-city': typeof HolyCityRoute
  '/makoto': typeof MakotoRoute
  '/miamah-comedy': typeof MiamahComedyRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/swell-life': typeof SwellLifeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chicos-shop-this-look': typeof ChicosShopThisLookRoute
  '/chicos-simply-soma': typeof ChicosSimplySomaRoute
  '/chicos-zoom': typeof ChicosZoomRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/holy-city': typeof HolyCityRoute
  '/makoto': typeof MakotoRoute
  '/miamah-comedy': typeof MiamahComedyRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/swell-life': typeof SwellLifeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chicos-shop-this-look'
    | '/chicos-simply-soma'
    | '/chicos-zoom'
    | '/contact'
    | '/error'
    | '/holy-city'
    | '/makoto'
    | '/miamah-comedy'
    | '/projects'
    | '/resume'
    | '/swell-life'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chicos-shop-this-look'
    | '/chicos-simply-soma'
    | '/chicos-zoom'
    | '/contact'
    | '/error'
    | '/holy-city'
    | '/makoto'
    | '/miamah-comedy'
    | '/projects'
    | '/resume'
    | '/swell-life'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chicos-shop-this-look'
    | '/chicos-simply-soma'
    | '/chicos-zoom'
    | '/contact'
    | '/error'
    | '/holy-city'
    | '/makoto'
    | '/miamah-comedy'
    | '/projects'
    | '/resume'
    | '/swell-life'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChicosShopThisLookRoute: typeof ChicosShopThisLookRoute
  ChicosSimplySomaRoute: typeof ChicosSimplySomaRoute
  ChicosZoomRoute: typeof ChicosZoomRoute
  ContactRoute: typeof ContactRoute
  ErrorRoute: typeof ErrorRoute
  HolyCityRoute: typeof HolyCityRoute
  MakotoRoute: typeof MakotoRoute
  MiamahComedyRoute: typeof MiamahComedyRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  SwellLifeRoute: typeof SwellLifeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChicosShopThisLookRoute: ChicosShopThisLookRoute,
  ChicosSimplySomaRoute: ChicosSimplySomaRoute,
  ChicosZoomRoute: ChicosZoomRoute,
  ContactRoute: ContactRoute,
  ErrorRoute: ErrorRoute,
  HolyCityRoute: HolyCityRoute,
  MakotoRoute: MakotoRoute,
  MiamahComedyRoute: MiamahComedyRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  SwellLifeRoute: SwellLifeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/chicos-shop-this-look",
        "/chicos-simply-soma",
        "/chicos-zoom",
        "/contact",
        "/error",
        "/holy-city",
        "/makoto",
        "/miamah-comedy",
        "/projects",
        "/resume",
        "/swell-life"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/chicos-shop-this-look": {
      "filePath": "chicos-shop-this-look.tsx"
    },
    "/chicos-simply-soma": {
      "filePath": "chicos-simply-soma.tsx"
    },
    "/chicos-zoom": {
      "filePath": "chicos-zoom.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/holy-city": {
      "filePath": "holy-city.tsx"
    },
    "/makoto": {
      "filePath": "makoto.tsx"
    },
    "/miamah-comedy": {
      "filePath": "miamah-comedy.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/resume": {
      "filePath": "resume.tsx"
    },
    "/swell-life": {
      "filePath": "swell-life.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
